icons_format = " {icon} "

[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_fg = "#ff007b"
idle_bg = "#011017"
warning_fg = "#ff0000"
warning_bg = "#011017"
alert_fg = "#ff003e"
alert_bg = "#011017"
info_fg = "#ff003e"
info_bg = "#011017"
separator = ""

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "focused_window"
format = "$title.str(w:100)"
# max_width = 100

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "nvidia_gpu"
interval = 1
format = "$icon $utilization.eng(w:3) $temperature $clocks.eng(w:4) "

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "net"
format = "$icon $device {$signal_strength $ssid $frequency|$ip} "

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon /: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/boot"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 1.0
alert = 0.5
format = "/boot: $available.eng(w:2) "

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:4)/$mem_total.eng(w:4) $icon_swap $swap_used.eng(w:4)/$swap_total.eng(w:4) "
format_alt = "$icon $mem_used.eng(w:4)/$mem_total.eng(w:4) $icon_swap $swap_used.eng(w:4)/$swap_total.eng(w:4) "

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "sound"
format = "$icon {$volume.eng(w:2) |}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = "echo "
[block.theme_overrides]
idle_fg = "#00aaff"

[[block]]
block = "cpu"
interval = 1
info_cpu = 40
warning_cpu = 50
critical_cpu = 90
format = "$icon $utilization.eng(w:3) $frequency.eng(w:4) $barchart "
format_alt = "$icon [1: $utilization1.eng(w:3) $frequency1.eng(w:4)] [2: $utilization2.eng(w:3) $frequency2.eng(w:4)] [3: $utilization3.eng(w:3) $frequency3.eng(w:4)] [4: $utilization4.eng(w:3) $frequency4.eng(w:4)]"

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"
